= CI/CD, le divorce serait-prononcé ?

[.notes]
--
On a eu tous les deux pas mal d'occasion de mettre en place des process CI/CD

Un d'origine Java et l'autre PHP
--

== Introduction

* Yann : Tech Lead d'origine PHP - Forte audience - Déploiement fréquent
* Nico : Tech Lead d'origine Java

* Les deux : aiment automatiser des trucs :)

=== Les raisons de la CI/CD

* S'assurer que le code produit soit de bonnes qualité et respecte les standards sur 15+ projets en parallèle
* Simplifier le testing fonctionnel / sécurité
* Accélérer la vitesse/fréquence de MEP via le déploiement auto
* S'assurer de la reproductibilité des différentes étapes (de l'env de dev à la livraison)
* Assurer un suivi niveau CP/Lead

* Automatiser un max de tache

[.notes]
--
Yann : c'est comme ça que je suis arrivée dedans.
A l'époque Docker n'était pas dans le game, j'ai commencé avec de la VM partagé, puis du Vagrant Puppet avec du capistrano
Symfony, les PSR, et composer (le package manager de PHP) n'existait pas, ou n'était pas connu
Donc c'était vraiment à la mano
--

=== Côté Nico

[.notes]
--
A voir si ce genre d'intro te va
--

=== D'un besoin personnel à la mission cliente

* D'abord perso : automatiser des taches redondantes
* Puis pour l'équipe : simplifier/industrialiser le build
* Puis pour un centre de compétence complet : unifier les pratiques
* Puis pour les managers : remonter des infos automatiquement sur le build
* Finalement en tant que mission à part entière : appliquer ces principes pour des clients

[.notes]
--
Ce process qui était à la base un outil interne pour nos équipes et devenu au final un outil "indispensable" pour toutes les équipes
Aujourd'hui, nous avons des missions exclusivement dédiées à la mise en place de CI/CD et d'automatisation/industrialisation.
--

=== La rencontre de deux mondes

* Les mêmes approches, concepts, etc.
* Pas la même implémentation ...
* ... Mais alors pas du tout

=== Nous sommes

Des psychologues de couples CI/CD
